### ISSUE TITLE
Feature request: Improve automation of source configuration

### ISSUE THREAD

**Issue by ezzatron** [jmalloc/grit#90]
I have dotfiles repos for a couple of my workplaces, and it's pretty difficult to have each repo manage its own Grit config at the moment. I end up having to write a Grit config generator that pulls in and combines Grit config from multiple sources, which is extra hard in a Bash script because it's TOML and I can't just use `jq`.

So if I could do something like `grit source set example 'git@github.example.org:{{slug}}.git'`, or alternatively have a config file like: 

```toml
# ~/.config/grit/example.toml
[clone.sources]
example = "git@github.example.org:{{slug}}.git"
```

It would be a cool improvement I think.
